### ISSUE TITLE
Trouble adding rocket league to games

### ISSUE THREAD

**Issue by ikrowni** [kabiiQ/obs-game-detection#1]
Hello after setting up the script as per the instructions I'm not able to get the game clips exporting to their respective folders.

```
Rocket League (64-bit, DX11, Cooked): Rocket League
Rocket League
```

![image](https://user-images.githubusercontent.com/4442098/200107928-2b3fb6c1-63b8-4b5b-bb92-7ace41502abf.png)

That's what I currently have inside the cfg file.  The replay buffer is starting when I launch OBS so I'm pretty sure the script is working. I installed python version you put into the instructions.

Here's some screenshots of the game

Task Manager
![image](https://user-images.githubusercontent.com/4442098/200107977-7bb27b81-8fd2-4ed2-a9e1-2a9253909f37.png)

![image](https://user-images.githubusercontent.com/4442098/200107999-8bdb4cd7-240b-49cd-b32c-3647ade76d8c.png)

**Comment by kabiiQ** [comment]
The exact executable name can be found in the Details tab of task manager. You can also right click the process -> "Go to details". 

I don't have Rocket League, so I can't confirm myself, but searching on the internet it looks like it will be RocketLeague.exe. So all you need to add to the games.cfg is `RocketLeague: Rocket League`
